SET
    FOREIGN_KEY_CHECKS = 0;

DROP TABLE usuario_tipo,
usuario_tema,
usuario,
mensaje,
informacion,
contacto,
institucion,
area,
especificacion,
alineacion,
participante_tipo,
modalidad,
duracion,
curso_modelo,
requisito,
objetivo,
contenido_primario,
contenido_secundario,
contenido_transversal,
estrategia,
evaluacion_diagnostica,
evaluacion_formativa,
evaluacion_final,
entorno_aprendizaje,
bibliografia,
curso,
curso_evento,
curso_deber,
curso_seccion,
seccion_video,
video_comentario,
video_respuesta,
seccion_leccion,
seccion_pregunta,
seccion_alternativa,
inscripcion,
inscripcion_leccion,
inscripcion_pregunta,
inscripcion_alternativa,
certificado_tipo,
certificado,
deber_entrega,
publicacion,
publicacion_comentario,
publicacion_respuesta,
buzon,
transaccion_tipo,
transaccion;

SET
    FOREIGN_KEY_CHECKS = 1;